# configs/marco_timbre.yaml
testname: "Timbre-Transfer MUSHRA"
testId: mushra_test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:
  # -------- Instructions --------
  - type: generic
    id: intro
    name: Instructions
    content: |
      You will hear multiple versions of the SAME musical phrase.
      Rate each condition on a 0–100 scale according to the question shown on that page.
      • "Content preservation": is the melody/rhythm/phrasing preserved vs the content (ctx)?
      • "Overall audio quality": judge artefacts (noise, distortion, warbles), clarity.
      • "Realism": does it sound like a real performance of the target instrument?
      Use good headphones in a quiet room. You can replay and adjust sliders anytime.

  # ========================= Clarinet → Strings =========================
  # ----- Take 1 -----
  - type: mushra
    id: Clarinet2Strings-1-content
    name: Clarinet→Strings (take 1) — Content preservation
    showWaveform: true
    reference: audio_data/Clarinet2Strings/1/ctx_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **content (melody/rhythm/phrasing) preservation** relative to the CONTENT example above.
      Ignore timbre; focus on whether the musical content is preserved.
      0 = not preserved at all • 100 = perfectly preserved
    stimuli:
      sys_bddm19: audio_data/Clarinet2Strings/1/bddm19_aligned.wav
      sys_wg6:    audio_data/Clarinet2Strings/1/wg6_aligned.wav
      sys_gen:    audio_data/Clarinet2Strings/1/gen_aligned.wav

  - type: mushra
    id: Clarinet2Strings-1-quality
    name: Clarinet→Strings (take 1) — Overall audio quality
    showWaveform: true
    reference: audio_data/Clarinet2Strings/1/ref_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **overall audio quality** (artefacts, noise, distortion, phasing, warbles, clarity).
      0 = very poor / heavy artefacts • 100 = excellent / clean
    stimuli:
      sys_bddm19: audio_data/Clarinet2Strings/1/bddm19_aligned.wav
      sys_wg6:    audio_data/Clarinet2Strings/1/wg6_aligned.wav
      sys_gen:    audio_data/Clarinet2Strings/1/gen_aligned.wav

  - type: mushra
    id: Clarinet2Strings-1-realism
    name: Clarinet→Strings (take 1) — Realism (Strings)
    showWaveform: true
    reference: audio_data/Clarinet2Strings/1/ref_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **realism/naturalness as STRINGS**, regardless of closeness to this reference timbre.
      0 = artificial/unnatural • 100 = very realistic/natural
    stimuli:
      sys_bddm19: audio_data/Clarinet2Strings/1/bddm19_aligned.wav
      sys_wg6:    audio_data/Clarinet2Strings/1/wg6_aligned.wav
      sys_gen:    audio_data/Clarinet2Strings/1/gen_aligned.wav

  # ----- Take 2 -----
  - type: mushra
    id: Clarinet2Strings-2-content
    name: Clarinet→Strings (take 2) — Content preservation
    showWaveform: true
    reference: audio_data/Clarinet2Strings/2/ctx_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **content preservation** relative to the CONTENT example (melody/rhythm/phrasing).
      Ignore timbre mismatch. 0 = none • 100 = perfect
    stimuli:
      sys_bddm19: audio_data/Clarinet2Strings/2/bddm19_aligned.wav
      sys_wg6:    audio_data/Clarinet2Strings/2/wg6_aligned.wav
      sys_gen:    audio_data/Clarinet2Strings/2/gen_aligned.wav

  - type: mushra
    id: Clarinet2Strings-2-quality
    name: Clarinet→Strings (take 2) — Overall audio quality
    showWaveform: true
    reference: audio_data/Clarinet2Strings/2/ref_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **overall audio quality** (artefacts, noise, distortion, phasing, warbles, clarity).
      0 = very poor • 100 = excellent
    stimuli:
      sys_bddm19: audio_data/Clarinet2Strings/2/bddm19_aligned.wav
      sys_wg6:    audio_data/Clarinet2Strings/2/wg6_aligned.wav
      sys_gen:    audio_data/Clarinet2Strings/2/gen_aligned.wav

  - type: mushra
    id: Clarinet2Strings-2-realism
    name: Clarinet→Strings (take 2) — Realism (Strings)
    showWaveform: true
    reference: audio_data/Clarinet2Strings/2/ref_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **realism/naturalness as STRINGS**, regardless of reference similarity.
      0 = artificial • 100 = very realistic
    stimuli:
      sys_bddm19: audio_data/Clarinet2Strings/2/bddm19_aligned.wav
      sys_wg6:    audio_data/Clarinet2Strings/2/wg6_aligned.wav
      sys_gen:    audio_data/Clarinet2Strings/2/gen_aligned.wav

  # ----- Take 3 -----
  - type: mushra
    id: Clarinet2Strings-3-content
    name: Clarinet→Strings (take 3) — Content preservation
    showWaveform: true
    reference: audio_data/Clarinet2Strings/3/ctx_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **content preservation** vs the CONTENT example (melody/rhythm/phrasing).
      0 = none • 100 = perfect
    stimuli:
      sys_bddm19: audio_data/Clarinet2Strings/3/bddm19_aligned.wav
      sys_wg6:    audio_data/Clarinet2Strings/3/wg6_aligned.wav
      sys_gen:    audio_data/Clarinet2Strings/3/gen_aligned.wav

  - type: mushra
    id: Clarinet2Strings-3-quality
    name: Clarinet→Strings (take 3) — Overall audio quality
    showWaveform: true
    reference: audio_data/Clarinet2Strings/3/ref_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **overall audio quality** (artefacts, noise, distortion, phasing, warbles, clarity).
      0 = very poor • 100 = excellent
    stimuli:
      sys_bddm19: audio_data/Clarinet2Strings/3/bddm19_aligned.wav
      sys_wg6:    audio_data/Clarinet2Strings/3/wg6_aligned.wav
      sys_gen:    audio_data/Clarinet2Strings/3/gen_aligned.wav

  - type: mushra
    id: Clarinet2Strings-3-realism
    name: Clarinet→Strings (take 3) — Realism (Strings)
    showWaveform: true
    reference: audio_data/Clarinet2Strings/3/ref_aligned.wav
    createAnchor35: false
    createAnchor70: false
    content: |
      Rate **realism/naturalness as STRINGS**, independent of reference similarity.
      0 = artificial • 100 = very realistic
    stimuli:
      sys_bddm19: aud_
