# test config mushra page, no waveform, 3 conditions,  looping


testname: MUSHRA without waveform
testId: mushra_nowav
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:
    - type: mushra
      id: trial2
      name: Mono Trial
      content: TEST MARCO
      showWaveform: false
      enableLooping: false 
      reference: audio_data/Clarinet2Strings/1/ref_aligned.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: audio_data/Clarinet2Strings/1/bddm19_aligned.wav
          C2: audio_data/Clarinet2Strings/1/wg6_aligned.wav
          C3: audio_data/Clarinet2Strings/1/gen_aligned.wav

    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day
      showResults: true
      writeResults: true
